/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 muza.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/muza.glb')
  return (
    <group {...props} dispose={null} scale={[3,3,5.5]}>
      <mesh geometry={nodes.COLLAR_TSHIRT.geometry} material={materials.Collar_Shader1} />
      <mesh geometry={nodes.FRONT_TSHIRT.geometry} material={materials.Front_Shader1} />
      <mesh geometry={nodes.LEFT_SLEEVE_TSHIRT.geometry} material={materials.Left_Sleeve_Shader1} />
      <mesh geometry={nodes.Pattern_1086885.geometry} material={materials.main_2677} />
      <mesh geometry={nodes.Pattern_2903483.geometry} material={materials['main Copy 1_2693']} />
      <mesh geometry={nodes.R_SLEEVE_TSHIRT.geometry} material={materials.Right_Sleeve_Shader2} />
      <mesh geometry={nodes.REAR_TSHIRT.geometry} material={materials.Rear_Shader1} />
      <mesh geometry={nodes.Stitch_389563.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389563001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_389591.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389591001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Topstitch_1642569.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3715} />
      <mesh geometry={nodes.Topstitch_1642569001.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3738} />
      <mesh geometry={nodes.Stitch_386715.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386715001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_386743.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386743001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392217.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392217001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392189.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392189001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
    </group>
  )
}

useGLTF.preload('/muza.glb')
